from django.urls import path
from .views import *

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('product/', Products.as_view(), name='product'),
    path('filial/', Filials.as_view(), name='filial'),
    path('saler/', Saler.as_view(), name='saler'),
    path('ombor/', Ombor.as_view(), name='ombor'),
    path('omborqabul/', OmborQabul.as_view(), name='omborqabul'),
    path('omborminus/', OmborMinus.as_view(), name='omborminus'),
    path('faktura/', Fakturas.as_view(), name='faktura'),
    path('fakturatarix/', FakturaTarix.as_view(), name='fakturatarix'),
    path('warefaktura/', WareFakturas.as_view(), name='warefaktura'),
    path('warefakturatarix/', WareFakturaTarix.as_view(), name='warefakturatarix'),
    path('getfakturaitem/', GetFakturaItem, name='getfakturaitem'),
    path('datafak/', DataFak, name='datafak'),
    path('table/', Table.as_view(), name='table'),
    path('datatable/', DataTable.as_view(), name='datatable'),
    path('hodim/', Hodim.as_view(), name='hodim'),
    path('debtor/', Debtors.as_view(), name='debtor'),
    path('debtorhistory/', DebtorHistory, name='debtorhistory'),
    path('deliverhistory/', DeliverHistory, name='deliverhistory'),
    path('deliver/', Delivers.as_view(), name='deliver'),
    path('profile/', Profile.as_view(), name='profile'),
    path('profile-setting/', ProfileSetting.as_view(), name='profile-setting'),
    path('sweet-alert/', SweetAlert.as_view(), name='sweet-alert'),
    path('date/', Date.as_view(), name='date'),
    path('widget/', Widget.as_view(), name='widget'),
    path('charthome/', ChartHome, name='charthome'),
    path('datahome/', DataHome, name='datahome'),
    path('dataware/', DataWare, name='dataware'),
    path('getitem/', GetItem, name='getitem'),
    path('summa/', Summa, name='summa'),
    path('filialkirim/', FilialKirim, name='filialkirim'),
    path('salerkirim/', SalerKirim, name='salerkirim'),
    # path('qol/', Qoldiq, name='qol'),
    path('nasiyatarix/', NasiyaTarix, name='nasiyatarix'),
]
