# Generated by Django 3.2 on 2021-05-18 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnProductToDeliver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('som', models.FloatField(default=0)),
                ('dollar', models.FloatField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('deliver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.deliver')),
            ],
            options={
                'verbose_name_plural': 'Return Product To Deliver',
            },
        ),
        migrations.CreateModel(
            name='ReturnProductToDeliverItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('som', models.FloatField(default=0)),
                ('dollar', models.FloatField(default=0)),
                ('quantity', models.FloatField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productfilial')),
                ('returnproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.returnproducttodeliver')),
            ],
            options={
                'verbose_name_plural': 'Return Product To Deliver Item',
            },
        ),
    ]
