# Generated by Django 3.2 on 2021-05-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_returnproducttodeliver_returnproducttodeliveritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnproducttodeliver',
            name='kurs',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
