# Generated by Django 3.2 on 2021-05-25 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210519_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnproducttodeliver',
            name='filial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.filial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='skidka_dollar',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='skidka_som',
            field=models.FloatField(default=0),
        ),
    ]
