# Generated by Django 3.2 on 2021-05-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210527_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliver',
            name='difference',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='deliver',
            name='dollar',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='deliver',
            name='phone1',
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliver',
            name='phone2',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='deliver',
            name='som',
            field=models.FloatField(default=0),
        ),
    ]
