# Generated by Django 3.2 on 2021-05-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210527_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pereotsenka',
            name='summa',
        ),
        migrations.AddField(
            model_name='pereotsenka',
            name='dollar',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pereotsenka',
            name='som',
            field=models.FloatField(default=0),
        ),
    ]
