# Generated by Django 3.2 on 2021-05-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210528_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='currency',
            new_name='difference_dollar',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='difference',
            new_name='difference_som',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='naqd',
            new_name='naqd_dollar',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='nasiya',
            new_name='naqd_som',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='summa',
        ),
        migrations.AddField(
            model_name='shop',
            name='nasiya_dollar',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='nasiya_som',
            field=models.FloatField(default=0),
        ),
    ]
