# Generated by Django 3.2 on 2021-05-28 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210528_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debtor',
            old_name='debts',
            new_name='dollar',
        ),
        migrations.RenameField(
            model_name='debtor',
            old_name='debts_dollar',
            new_name='som',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='difference_dollar',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='difference_som',
        ),
    ]
