# Generated by Django 3.2 on 2021-05-28 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210528_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returnproduct',
            old_name='summa',
            new_name='som',
        ),
    ]
