# Generated by Django 3.2 on 2021-05-28 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_summa_returnproduct_som'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payhistory',
            old_name='sum',
            new_name='som',
        ),
    ]
