# Generated by Django 3.2 on 2021-05-29 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_sum_payhistory_som'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changeprice',
            name='dollar',
        ),
        migrations.RemoveField(
            model_name='changeprice',
            name='som',
        ),
    ]
