# Generated by Django 3.2 on 2021-05-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210529_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='return_sum',
        ),
        migrations.AddField(
            model_name='debt',
            name='som',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='debt',
            name='dollar',
            field=models.FloatField(default=0),
        ),
    ]
