# Generated by Django 3.2 on 2021-06-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_debtdeliver_deliverpayhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverpayhistory',
            options={'verbose_name_plural': 'Deliver Tolov Tarixi'},
        ),
        migrations.RenameField(
            model_name='faktura',
            old_name='difference',
            new_name='difference_som',
        ),
        migrations.AddField(
            model_name='faktura',
            name='difference_dollar',
            field=models.FloatField(default=0),
        ),
    ]
